[package]
name = "gbi"
version = "0.1.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2018"

# [lib]
# name = "gbi"
# path = "src/lib.rs"

[[bin]]
name = "gbi"
path = "main.rs"

[dependencies]
# gbi_apu = { path = "crates/apu" }
# gbi_gui = { path = "crates/gui" }
# gbi_vst3 = { path = "crates/vst3" }
