[package]
name = "gbi"
version = "0.1.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2018"
description = "A VST3 instrument to do GameBoy"

[lib]
crate-type = ["cdylib"]

[dependencies]
vst3-sys = { version = "0.1.0", git = "https://github.com/RustAudio/vst3-sys" }
