[package]
name = "soyboy-sp"
version = "0.1.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2018"
description = "A VST3 instrument to do some chiptunes"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]

[dependencies]
vst3-sys = { version = "0.1.0", git = "https://github.com/RustAudio/vst3-sys" }
vst3-com = { version = "0.1.0", git = "https://github.com/RustAudio/vst3-sys" }

widestring = "0.4.0"
